[versions]
kotlin = "2.2.21"
kotlin-coroutine = "1.10.2"
spring-boot = "4.0.0-M2"
spring-dependency-management = "1.1.7"
spring-modulith = "2.0.0-RC1"
junit = "5.11.0"
junit-platform = "1.11.2"
assert4j = "3.26.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }

[libraries]
kotlin-stblib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutine" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutine" }

spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter"}
spring-boot-starter-aop = { module = "org.springframework.boot:spring-boot-starter-aop"}
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web"}
spring-boot-starter-data-jdbc = { module = "org.springframework.boot:spring-boot-starter-data-jdbc"}
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test"}

spring-modulith-bom = { module = "org.springframework.modulith:spring-modulith-bom", version.ref = "spring-modulith" }
spring-modulith-starter-core = { module = "org.springframework.modulith:spring-modulith-starter-core" }
spring-modulith-starter-jdbc = { module = "org.springframework.modulith:spring-modulith-starter-jdbc" }
spring-modulith-starter-test = { module = "org.springframework.modulith:spring-modulith-starter-test" }

h2 = { module = "com.h2database:h2" }

kotlin-junit-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

junit-engine-jupiter = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assert4j" }
